spring:
    datasource:
        username: root
        password:
        url: jdbc:mysql://localhost:3306/esm_stdio
    jpa:
        show-sql: true
        properties:
          hibernate:
              format_sql: true
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    mail:
        host: smtp.gmail.com
        port: 587
        username: anhtayd27111997@gmail.com
        password: gykvowskfehznjzr
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
application:
    security:
        password-secret: "ESM"
        duration-accessToken: 604800000
        duration-refreshToken: 1036800000
        token-prefix: "Bearer"
        authorization-header: "Authorization"
    pagination:
        default_page_size: 5
server:
    port: 8089
    servlet:
        contextPath: /api
springdoc:
    api-docs:
        path: /openapi-docs
    swagger-ui:
        path: /openapi-docs/gui.html
